CREATE TABLE IF NOT EXISTS summaries (
    id SERIAL PRIMARY KEY,
    video_id VARCHAR(255) UNIQUE,
    video_url TEXT,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    transcript TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_video_id ON summaries (video_id);

CREATE TABLE IF NOT EXISTS flashcards(
    id SERIAL PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folders(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)